spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simulacion_vial
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: clave-secreta-sbvia-uteq-2026-minimo-32-caracteres
  expiration: 3600000
  refresh-expiration: 604800000